# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '7.1'

target 'Vista' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'p2pkit', '2.0.4'
end
